<!-- Gera o menu de navegação -->
<hr />

<?php if (isset($_SESSION['username'])) : ?>
    <a href="./">Home</a> &#10084; 
    <a href="./?route=viewprofile">Visualizar Perfil</a> &#10084; 
    <a href="./?route=editprofile">Editar Perfil</a> &#10084; 
    <a href="./?route=questionnaire">Questionário</a> &#10084; 
    <a href="./?route=mymismatch">Meu Mismatch</a> &#10084; 
    <a href="./?route=logout">Sair (<?= $_SESSION['username'] ?>)</a>
<?php else : ?>
    <a href="./?route=login">Entrar</a> &#10084; 
    <a href="./?route=signup">Cadastrar</a>
<?php endif ?>
<hr />